// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_U0BBepiBZHdW0jfAh2HYRt1QMnKFmPo',
    appId: '1:138796959583:web:51c946e2cb538ae20f98ea',
    messagingSenderId: '138796959583',
    projectId: 'nikah-app-f6b2a',
    authDomain: 'nikah-app-f6b2a.firebaseapp.com',
    storageBucket: 'nikah-app-f6b2a.firebasestorage.app',
    measurementId: 'G-PFHSVM09KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymLpOB_u9Q2eRdmViMHkPqg-iXsPrcHY',
    appId: '1:138796959583:android:4ef46920e58aa47c0f98ea',
    messagingSenderId: '138796959583',
    projectId: 'nikah-app-f6b2a',
    storageBucket: 'nikah-app-f6b2a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXpq-1Io9rL1ssdDCq9DjvPcOHoKGKLbM',
    appId: '1:138796959583:ios:f8890914d03698dd0f98ea',
    messagingSenderId: '138796959583',
    projectId: 'nikah-app-f6b2a',
    storageBucket: 'nikah-app-f6b2a.firebasestorage.app',
    iosBundleId: 'com.example.lgoinUi',
  );
}
