class RishtaModel {
  final String id;
  final String name;
  final int age;
  final String city;
  final String profession;
  final String imagePath; // asset path ya network url
  final String contactNumber;

  RishtaModel({
    required this.id,
    required this.name,
    required this.age,
    required this.city,
    required this.profession,
    required this.imagePath,
    required this.contactNumber,
  });
}

// Demo data - aap ye baad mein Firebase/Firestore se bhi la saken gay
//
// NOTE: Filhal sirf 8 images hain (1.jpg se 8.jpg), isliye naye 20 rishton ke
// liye unhi images ko cycle/repeat kiya gaya hai. Jab aap ke paas nayi images
// aayen, to neeche har entry ka "imagePath" apni actual image se update kar den.
// "contactNumber" bhi placeholder hai — apna asal number daal den.
List<RishtaModel> demoRishtayList = [
  RishtaModel(
    id: 'r1',
    name: 'Ayesha Khan',
    age: 24,
    city: 'Lahore',
    profession: 'Teacher',
    imagePath: 'images/1.jpg',
    contactNumber: '0300-0000001',
  ),
  RishtaModel(
    id: 'r2',
    name: 'Fatima Ali',
    age: 26,
    city: 'Karachi',
    profession: 'home',
    imagePath: 'images/2.jpg',
    contactNumber: '0300-0000002',
  ),
  RishtaModel(
    id: 'r3',
    name: 'Zainab Malik',
    age: 23,
    city: 'Islamabad',
    profession: 'home work',
    imagePath: 'images/3.jpg',
    contactNumber: '0300-0000003',
  ),
  RishtaModel(
    id: 'r4',
    name: 'Hina Ahmed',
    age: 27,
    city: 'Faisalabad',
    profession: 'student',
    imagePath: 'images/4.jpg',
    contactNumber: '0300-0000004',
  ),
  RishtaModel(
    id: 'r5',
    name: 'Sara Iqbal',
    age: 25,
    city: 'Multan',
    profession: 'Designer',
    imagePath: 'images/5.jpg',
    contactNumber: '0300-0000005',
  ),
  RishtaModel(
    id: 'r6',
    name: 'Mahnoor Sheikh',
    age: 22,
    city: 'Rawalpindi',
    profession: 'Student',
    imagePath: 'images/6.jpg',
    contactNumber: '0300-0000006',
  ),
  RishtaModel(
    id: 'r7',
    name: 'Amna Yousaf',
    age: 28,
    city: 'Peshawar',
    profession: 'home ka kam',
    imagePath: 'images/7.jpg',
    contactNumber: '0300-0000007',
  ),
  RishtaModel(
    id: 'r8',
    name: 'Noor Fatima',
    age: 24,
    city: 'Sialkot',
    profession: 'selaye ka kam',
    imagePath: 'images/8.jpg',
    contactNumber: '0300-0000008',
  ),
  RishtaModel(
    id: 'r9',
    name: 'norren Ahmed',
    age: 23,
    city: 'Lahore',
    profession: ' home',
    imagePath: 'images/9.jpg',
    contactNumber: '0300-0000009',
  ),
  RishtaModel(
    id: 'r10',
    name: 'uzma Tariq',
    age: 22,
    city: 'Karachi',
    profession: 'talaq yafta',
    imagePath: 'images/10.jpg',
    contactNumber: '0300-0000010',
  ),
  RishtaModel(
    id: 'r11',
    name: 'aliha Sheikh',
    age: 23,
    city: 'Islamabad',
    profession: 'home work',
    imagePath: 'images/11.jpg',
    contactNumber: '0300-0000011',
  ),
  RishtaModel(
    id: 'r12',
    name: 'abiha',
    age: 22,
    city: 'Faisalabad',
    profession: 'work',
    imagePath: 'images/12.jpg',
    contactNumber: '0300-0000012',
  ),
  RishtaModel(
    id: 'r13',
    name: 'Zara Malik',
    age: 25,
    city: 'Multan',
    profession: 'Architect',
    imagePath: 'images/13.jpg',
    contactNumber: '0300-0000013',
  ),
  RishtaModel(
    id: 'r14',
    name: 'Rabia Hussain',
    age: 23,
    city: 'Rawalpindi',
    profession: 'Pharmacist',
    imagePath: 'images/14.jpg',
    contactNumber: '0300-0000014',
  ),
  RishtaModel(
    id: 'r15',
    name: 'Sana Aslam',
    age: 26,
    city: 'Peshawar',
    profession: 'Teacher',
    imagePath: 'images/15.jpg',
    contactNumber: '0300-0000015',
  ),
  RishtaModel(
    id: 'r16',
    name: 'Maria Nawaz',
    age: 24,
    city: 'Sialkot',
    profession: ' Designer',
    imagePath: 'images/16.jpg',
    contactNumber: '0300-0000016',
  ),
  RishtaModel(
    id: 'r17',
    name: 'lubna Malik',
    age: 25,
    city: 'Lahore',
    profession: 'selaye ka kam',
    imagePath: 'images/17.jpg',
    contactNumber: '0300-0000017',
  ),
  RishtaModel(
    id: 'r18',
    name: 'aliza khan',
    age: 24,
    city: 'Karachi',
    profession: 'Accountant',
    imagePath: 'images/18.jpg',
    contactNumber: '0300-0000018',
  ),
  RishtaModel(
    id: 'r19',
    name: 'salma Qureshi',
    age: 21,
    city: 'Islamabad',
    profession: 'worker',
    imagePath: 'images/19.jpg',
    contactNumber: '0300-0000019',
  ),
  RishtaModel(
    id: 'r20',
    name: 'Iqra Siddiqui',
    age: 22,
    city: 'Faisalabad',
    profession: 'HR',
    imagePath: 'images/20.jpg',
    contactNumber: '0300-0000020',
  ),
  RishtaModel(
    id: 'r21',
    name: 'Nida Farooq',
    age: 25,
    city: 'Multan',
    profession: ' Writer',
    imagePath: 'images/21.jpg',
    contactNumber: '0300-0000021',
  ),
  RishtaModel(
    id: 'r22',
    name: 'bushra Khan',
    age: 22,
    city: 'Rawalpindi',
    profession: 'hotel worker',
    imagePath: 'images/22.jpg',
    contactNumber: '0300-0000022',
  ),
  RishtaModel(
    id: 'r23',
    name: 'anela',
    age: 27,
    city: 'Peshawar',
    profession: 'worker',
    imagePath: 'images/23.jpg',
    contactNumber: '0300-0000023',
  ),
  RishtaModel(
    id: 'r24',
    name: 'Momina Rashid',
    age: 23,
    city: 'Sialkot',
    profession: 'Fashion ',
    imagePath: 'images/24.jpg',
    contactNumber: '0300-0000024',
  ),
  RishtaModel(
    id: 'r25',
    name: 'Bushra Naveed',
    age: 26,
    city: 'Lahore',
    profession: 'Psychologist',
    imagePath: 'images/25.jpg',
    contactNumber: '0300-0000025',
  ),
  RishtaModel(
    id: 'r26',
    name: 'sonia Iqbal',
    age: 33,
    city: 'Karachi',
    profession: 'Entrepreneur',
    imagePath: 'images/26.jpg',
    contactNumber: '0300-0000026',
  ),
  RishtaModel(
    id: 'r27',
    name: 'alina Aziz',
    age: 28,
    city: 'Islamabad',
    profession: 'IT Consultant',
    imagePath: 'images/27.jpg',
    contactNumber: '0300-0000027',
  ),
  RishtaModel(
    id: 'r28',
    name: 'Sidra Yaqoob',
    age: 24,
    city: 'Faisalabad',
    profession: 'home',
    imagePath: 'images/28.jpg',
    contactNumber: '0300-0000028',
  ),
  RishtaModel(
    id: 'r29',
    name: 'yasmeen',
    age: 23,
    city: 'kohat',
    profession: 'home',
    imagePath: 'images/29.jpg',
    contactNumber: '0300-0000028',
  ),
  RishtaModel(
    id: 'r30',
    name: 'noor',
    age: 22,
    city: 'islamabad',
    profession: 'worker',
    imagePath: 'images/30.jpg',
    contactNumber: '0300-0000028',
  ),
];
